config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :bookings, only: [:show]
  resources :clothes, only: [:index, :show, :new, :create] do
    resources :bookings, only: [:new, :create]
  end
  # Defines the root path route ("/")
  # root "articles#index"
  get "dashboard", to: "pages#dashboard"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :clothe
  belongs_to :user
  validates :start_date, :end_date, :user, presence: true
  validates :status, inclusion: { in: [ true, false ] }
end

app/models/clothe.rb
class Clothe < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
  validates :title, :category, :description, :price, :address, presence: true
  include PgSearch::Model
  pg_search_scope :search_by_title_and_description,
  against: [ :title, :description ],
  using: {
    tsearch: { prefix: true }
  }
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings, dependent: :destroy
  has_many :clothes, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, only: :dashboard

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  def after_sign_in_path_for(resource)
    dashboard_path
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = Booking.all
  end

  def show
    @booking = Booking.find(params[:id])
    @clothe_id = @booking.clothe.id
    @clothe = Clothe.find(@clothe_id)
  end

  def new
    @booking = Booking.new
    @clothe = Clothe.find(params[:clothe_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @clothe = Clothe.find(params[:clothe_id])
    @booking.user = current_user
    @booking.clothe = @clothe
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:status, :start_date, :end_date)
  end
end

app/controllers/clothes_controller.rb
class ClothesController < ApplicationController
  def index
    @clothes = Clothe.all
  end

  def show
    @clothe = Clothe.find(params[:id])
  end

  def new
    @clothe = Clothe.new
  end

  def create
    @clothe = Clothe.new(clothe_params)
    @clothe.user = current_user
    if @clothe.save
      redirect_to clothe_path(@clothe.id)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @clothe = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to clothes_path, status: :see_other
  end

  private

  def clothe_params
    params.require(:clothe).permit(:title, :description, :category, :price, :address, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def dashboard
    @bookings = Booking.where(user_id: current_user.id)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="container">
  <h1> <%= @clothe.title %> </h1>
  <%# commented line <h2> <strong> <%= Clothe.find(params[:clothe_id]).price € </strong> per day </h2> %>
  <div class="booking-image">
  <%= cl_image_tag @clothe.photo.key,
      width: 400, height: 300, crop: :fill %>
  </div>
<%= simple_form_for [@clothe, @booking],
                    html: {
                      data: {
                        controller: 'flatpickr'
                      }
                    } do |f| %>
  <%= f.input :start_date,
              as: :string,
              input_html: {
                data: {
                  flatpickr_target: 'startDateInput',
                }
              } %>
  <%= f.input :end_date,
              as: :string,
              input_html: {
                class: '',
                data: {
                  flatpickr_target: 'endDateInput'
                }
              } %>
   <%= f.input :status, as: :select, collection: [['Booked',true], ['Completed',false]] %>
  <%= f.submit "Book", class: "btn btn-primary" %>
  <p>No amount will be debited at this time</p>
  <p> <strong> Total <%= @clothe.price %> € </strong> </p>
<% end %>
  <%= link_to "Back", clothe_path(params[:clothe_id]), class: "btn btn-primary" %>
</div>

app/views/bookings/show.html.erb
<div class="container">
  <h1>Your booking for <%= @clothe.title %> </h1>
  <p> Lent by <%= @booking.user.first_name %> </p>
  <div class="card">
    <p> Booked from : <%= @booking.start_date %> To : <%= @booking.end_date %></p>
    <p> Category : <%= @clothe.category %></p>
    <p> Details : <%= @clothe.description %></p>
  </div>
<%= link_to "Back to my bookings", dashboard_path, class: "btn btn-primary" %>
</div>

app/views/clothes/index.html.erb
    <!-- Your content -->
    <div class="container">
      <h1><strong>Rented -</strong>Catalog</h1>
      <div class="clothes">
          <% @clothes.each do |c| %>
            <div class="card-product" %>
              <%= c.title %>
              <%= cl_image_tag c.photo.key,  width: 400, height: 300, crop: :fill%>
                <div class="card-product-infos">
                    <%= c.description %>
                    <p> <strong> <%= c.price %> € </strong> </p>
                </div>
              <p><%= link_to "Show this piece of clothe", clothe_path(c.id), class: "btn btn-primary" %> </p>
              <p><%= link_to "Delete", clothe_path(c.id), class: "btn btn-primary", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %> </p>
          </div>
          <% end %>
      </div>
    <%= link_to "Create a new piece of clothe", new_clothe_path, class: "btn-clothes" %>
    </div>

    <!-- Your script tags here -->
    <!-- <script src="first_file.js"></script> -->
    <!-- <script src="other_file.js"></script> -->

app/views/clothes/new.html.erb
<div class="container">
  <h1>Create your new piece of clothe that you want to rent:</h1>
  <%= simple_form_for @clothe do |b| %>
  <%= b.input :title, placeholder: "Choose a title for your piece of clothe" %>
  <%= b.input :description, placeholder: "Describe your piece of clothe" %>
  <%= b.input :address, placeholder: "Please fill in the address" %>
  <%= b.label :category %>
  <%= b.select :category,[['Dress','Dress'],['Tshirt','Tshirt'],['Pants','Pants'],['Shirt','Shirt'], ['Shorts','Shorts'], ['Shoes','Shoes'], ['Jacket','Jacket'], ['Onesie','Onesie'], ['Parka','Parka'], ['Skirt','Skirt'],['Body','Body']] %>
  <%= b.number_field :price, placeholder: "Choose the price you want to rent at" %>
  <%= b.input :photo, as: :file %>
  <%= b.submit "Add", class: "btn btn-primary" %>
  <% end %>

  <p>
      <%= link_to "Show all clothes", clothes_path, class: "btn btn-primary" %>
    </p>
</div>

app/views/clothes/show.html.erb
<h1><b>All my clothes</b></h1>
<div class="container">
  <h1><%= @clothe.title %></h1>
  <%= cl_image_tag @clothe.photo.key,
      width: 400, height: 300, crop: :fill %>
  <h3>Category: <%=@clothe.category %></h3>
  <h3>Description: <%=@clothe.description %></h3>
  <h3>Available at: <%=@clothe.address %></h3>
  <h3><%=@clothe.price%> €</h3>

<p>
  <%= link_to "Show all clothes", clothes_path(@clothe.id), class: "btn btn-primary" %>
</p>

<p>
  <%= link_to "Book this piece of clothe", new_clothe_booking_url(@clothe.id), class: "btn btn-primary" %>
</p>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rented</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
   <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>
   <%= render "shared/navbar" %>
   <%= render "shared/flashes" %>
    <%= yield %>
  </body>
  <script>
    const icaune = document.querySelector('.icaune');
    const search = document.querySelector('.search');
    console.log('hello')
    icaune.onclick = function () {
      search.classList.toggle('active')
    }
  </script>
</html>

app/views/pages/dashboard.html.erb
<div class="container">
  <h1>My Bookings</h1>
  <h2> Current Bookings </h2>
  <% @bookings.each do |b| %>
    <% if b.status == true && b.user_id == current_user.id %>
      <div class="booking-card">
        <div class="booking-image">
          <%= cl_image_tag Clothe.find(b.clothe_id).photo.key,  width: 400, height: 300, crop: :fill%>
        </div>
        <div class="booking-info">
          <h3> <%= Clothe.find(b.clothe_id).title %> </h3>
          <p> Category : <%= Clothe.find(b.clothe_id).category %></p>
          <p> Booked from : <%= b.start_date %> To : <%= b.end_date %> </p>
        </div>
          <%# <%= link_to "View more", booking_path(b.id), class: "btn btn-primary" %>
      </div>
    <% end %>
  <% end %>
  <% if @bookings.length == 0 %>
    <div class="no-booking-card">
      <h3>No clothes booked... yet!</h3>
      <p>It's time to refresh your wardrobe and get ready for your next fashion statement.</p>
      <%= link_to "Start searching", clothes_path, class: "btn-clothes-index" %>
      </div>
  <% end %>
  <h2> Previous Bookings </h2>
  <div class="booking-card">
    <% @bookings.each do |b| %>
      <% if b.status == false && b.user_id == current_user %>
        <h3> <%= Clothe.find(b.clothe_id).title %> </h3>
        <p> Category : <%= Clothe.find(b.clothe_id).category %></p>
        <p> Booked from : <%= b.start_date %> To : <%= b.end_date %> </p>
        <%= link_to "View more", booking_path(b.id), class: "btn btn-primary" %>
      <% end %>
    <% end %>
    </div>
</div>

app/views/pages/home.html.erb
<div class="banner">
  <div class="left-column">
    <h1>RENT<span>ED</span></h1>
    <h3><strong>Rent to Look Good,<span> Lend to Earn Good!</span></strong></h3>
    <p>Sign up today to rent or lend your clothing, and you'll be on your way<br>to looking your best!</p>
    <div class="sign-in-btn">
      <%= link_to "Sign in", new_user_session_path %>
    </div>
  </div>
  <div class="right-column">
  <%= image_tag("girl_clothe.png") %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo_rented.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="search">
      <div class="icaune"><i class="fa-solid fa-magnifying-glass"></i></div>
      <div class="input">
        <input type="text" placeholder="Search" id="mysearch">
        <span class="clear" onclick="document.getElementById('mysearch').value = ''"><i class="fa-solid fa-xmark"></i></span>
      </div>
    </div>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "See all clothes", clothes_path, class: "nav-link" %> <i class="fa-solid fa-shirt"></i>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/shiningmoonsunshine", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Bookings", dashboard_path, class: "dropdown-item" %>
              <%= link_to "Wishlist (soon)", "#", class: "dropdown-item" %>
              <%= link_to "Manage listings", "#", class: "dropdown-item" %>
              <%= link_to "Lend my clothes", new_clothe_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
<%#   <script>
    const icon = document.querySelector('.icon');
    const search = document.querySelector('.search');
    console.log('hello')
    icon.onclick = function () {
      search.classList.toggle('active')
    }
  </script> %>
</div>